### ISSUE TITLE
Depends on server-provided "changed" version

### ISSUE THREAD

**Issue by ef4** [ef4/ember-data-relationship-tracker#3]
This addon was an extraction from an app, and I've realized that it is depending on some behavior of that app's particular server: it expects the server to set a `changed` timestamp on each record.

We can it adjust it to not depend on that, but as it is it won't work right with servers that don't do this.

**Comment by scottkidder** [comment]
I think I've worked around this with
`
   trackedModel._relationshipTracker = Object.create(null);
   trackedModel.propertyDidChange('hasDirtyRelationships');
`

Maybe this mixin could become part of the https://github.com/poteto/ember-changeset/ project.

**Comment by ef4** [comment]
I don't think that workaround will be correct under all conditions. I think we truly need a bit of server-provided state here, because the point is to track whether it's dirty *relative to the server*. 

> Maybe this mixin could become part of the https://github.com/poteto/ember-changeset/ project.

I think this addon is just trying to fill a gap that should be rolled into ember-data itself. Hopefully it doesn't need to exist forever.

ember-changeset is also cool but it takes a different overall approach. It's about managing changes before they're applied to an object, this addon is about managing changes after they've been applied.

**Comment by ef4** [comment]
This is fixed now, as long as you provide a `version` field.

**Comment by cecemel** [comment]
Would it be possible to elaborate a bit on when you exactly need this version attribute? Still not fully clear to me.
Nice addon by the way.
